version:
  config: 2

run:
  timeout: 5m
  skip-dirs:
    - .idea

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - revive
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errcheck
